# Generated by Django 3.0.5 on 2020-05-13 13:46

from django.db import migrations, models
import sonsuz_website.news.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=sonsuz_website.news.models.NewsImage.image_upload_to, verbose_name='图片')),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=sonsuz_website.news.models.News.image_upload_to, verbose_name='封面'),
        ),
    ]
