# Generated by Django 3.0.5 on 2020-05-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200513_2146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='news',
            name='cover',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='封面'),
        ),
    ]
