# Generated by Django 3.0.5 on 2020-06-27 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userfollow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfollow',
            old_name='follower',
            new_name='follow_to',
        ),
    ]
