# Generated by Django 3.0.5 on 2020-05-31 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200530_1517'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecategory',
            options={'ordering': ['created_at'], 'verbose_name': '文章分类'},
        ),
        migrations.AddField(
            model_name='articlecategory',
            name='summary',
            field=models.TextField(blank=True, verbose_name='简介'),
        ),
    ]
