# Generated by Django 3.0.5 on 2020-06-09 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200609_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collect',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collect_article', to='blog.Article', verbose_name='收藏文章'),
        ),
        migrations.RemoveField(
            model_name='collect',
            name='category',
        ),
        migrations.AddField(
            model_name='collect',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='blog.ArticleCategory'),
        ),
    ]
