# Generated by Django 3.0.5 on 2020-06-10 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200609_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collect',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='collect', to='blog.CollectCategory'),
        ),
    ]
