# Generated by Django 3.0.5 on 2020-06-10 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200610_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collect',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='collect', to='blog.CollectCategory'),
        ),
    ]
