# Generated by Django 3.0.5 on 2020-06-18 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_categoryfollow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryfollow',
            name='category',
        ),
        migrations.AddField(
            model_name='categoryfollow',
            name='category',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='category_follow', to='blog.ArticleCategory'),
            preserve_default=False,
        ),
    ]
